string dccommsId
uint32 type
uint32 mac
string frameId
uint32 maxTxFifoSize

#bitrate = bps
uint32 bitrate

#Transmitted signal power (W).
float64 PT

#Power consumption for transmission (W). Default is 0.660 (1.6W).
uint32 PTConsume

#Power consumption for reception (W). Default is 0.395 (1.2W).
uint32 PRConsume

#Idle power consumption (W). Default is 0.0 (0W).
uint32 PIdle

#Mac protocol
# 0: broadcast MAC
# 1: T-MAC
# 2: FAMA
# 3: Slotted-FAMA
# 4: UWAN-MAC
# 5: COPE-MAC
# 6: ALOHA
# 7: R-MAC
# 8: GOAL

#Routing protocol
# 0: VBF
# 1: VBVA
# 2: DBR
# 3: Static
# 4: Dynamic
# 5: Dummy

---
bool res
