string dccommsId
uint32 mac
string frameId
uint32 maxTxFifoSize

float64 bitrate
float64 bitrateSd

uint32 maxDistance
uint32 minDistance

#Error rate: 0.0 - 1.0
float64 minPktErrorRate
float64 pktErrorRateIncPerMeter

#Rate Error Model (ns3):
string errorRateExpr
string errorUnit

#logging
string logLevel

---
bool res
