uint8 devType
string iddev
string frameId
uint8 mac
uint32 maxBitRate
float32 trTimeMean
float32 trTimeSd
float32 minPrTime
float32 prTimeIncPerMeter

#Error rate: 0.0 - 1.0
float64 minPktErrorRate
float64 pktErrorRateIncPerMeter

#distance in cm
uint32 maxDistance
uint32 minDistance
---
bool res
